global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['productservice:8080']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventoryservice:8080']

  - job_name: 'order-service'
    static_configs:
      - targets: ['orderservice:8080']

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricingservice:8080']

  - job_name: 'customer-service'
    static_configs:
      - targets: ['customerservice:8080']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notificationservice:8080']
  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:8080']