{
 "title": "ECommerce Microservices Dashboard",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Average latency (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[1m]) / rate(http_server_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[1m])"
    }
   ]
  }
 ]
}